version: '3.8'
services:
  api-server:
    image: docker.io/tabeldata/api-server:ee58423f
    ports:
      - 8081
    volumes:
      - ./api-server.env:/app/.env

  api-middleware: 
    image: docker.io/tabeldata/middleware-openapi:a16b11fb
    entrypoint: 
    - java
    - -Djava.security.egd=file:/dev/./urandom
    command: 
    - -jar
    - spring-boot.jar
    ports:
      - 8080
    env_file:
      - path: ./api-core.env
      - path: ./database.env
      - path: ./keycloack.env
      - path: ./clickhouse.env

  keycloack: 
    image: quay.io/keycloak/keycloak:25.0.2
    command: ["start-dev"]
    ports:
      - 82:8080
      - 9000
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_PROXY=edge

  api-portal-webapp:
    image: docker.io/tabeldata/api-management-webapp:7c72b8d9
    volumes:
      - ./nginx.default.conf.template.conf:/etc/nginx/templates/default.conf.template

  admin-webapp:
    image: docker.io/tabeldata/portal-api:3d7436bd
    volumes:
      - ./nginx.default.conf.template.conf:/etc/nginx/templates/default.conf.template
  
  reverse-proxy:
    image: nginx:mainline
    depends_on:
      - api-portal-webapp
      - admin-webapp
    ports:
      - 81:80
    volumes:
      - ./nginx.reverse-proxy.conf.template.conf:/etc/nginx/templates/default.conf.template
  